
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package com.farmacia.views.producto;

import com.farmacia.conponentes.Formulario;
import com.farmacia.dao.CRUD;
import com.farmacia.entities1.CategoriaProducto;
import com.farmacia.entities1.EnvaseProducto;
import com.farmacia.entities1.Iva;
import com.farmacia.entities1.Listar_usuario;
import com.farmacia.entities1.MarcaProducto;
import com.farmacia.entities1.MedidaProducto;
import com.farmacia.entities1.Productos;
import com.farmacia.entities1.TipoProducto;
import com.farmacia.fecha.Fecha;
import com.farmacia.validaciones.Validacion;
import com.farmacia.views.compras.AgregarCategoria;
import com.farmacia.views.compras.AgregarEnvase;
import com.farmacia.views.compras.AgregarMarca;
import com.farmacia.views.compras.AgregarMedida;
import com.farmacia.views.compras.AgregarTipo;
import com.farmacia.views.precios.Ingreso_de_Precios;
import com.farmacia.views.precios.Mantenimiento_Precios_Productos;
import java.awt.Color;

import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import sistemafarmacia.presentacion.FrmPrincipal;

/**
 *
 * @author guest-qzjm76
 */
public class Products extends javax.swing.JDialog {

    int x, y;
    CRUD crud = new CRUD();
    String CADENA = "";
    ArrayList<TipoProducto> lista = crud.listarTodoTipoProductos1();
    ArrayList<MedidaProducto> listam = crud.listarTodoMedidasProductos();
    ArrayList<EnvaseProducto> listae = crud.listarTodoEnvaseProductos();
    ArrayList<MarcaProducto> listama = crud.listarTodoMarcaProductos();
    ArrayList<CategoriaProducto> listaca = crud.listarTodoCategoriaProductos();
    ArrayList<Iva> listaIva = crud.listarTodoIvaProducto();
    Long id_tipo, id_medida, id_envase, id_marca, id_categoria;
    String error = "", IVA = "", valorIDProd = "";

    //,RECETA = "";
    public Products(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        getContentPane().setBackground(Color.white);
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);

        cbxTipos.setModel(Formulario.listarComboTipoPro(lista));
        cbxMedida.setModel(Formulario.listarComboMedidaPro(listam));
        cbxEnvase.setModel(Formulario.listarComboEnvasePro(listae));
        cbxMarca.setModel(Formulario.listarComboMarcaPro(listama));
        cbxIva.setModel(Formulario.listarComboIva(listaIva));
        cbcCategoria.setModel(Formulario.listarComboCategoriaPro(listaca));
        txtFechaActual.setText(FechaActual());
        Habilitar(false);

    }

    public Products(java.awt.Frame parent, boolean modal, Listar_usuario obj) {
        super(parent, modal);
        getContentPane().setBackground(Color.white);
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);

        cbxTipos.setModel(Formulario.listarComboTipoPro(lista));
        cbxMedida.setModel(Formulario.listarComboMedidaPro(listam));
        cbxEnvase.setModel(Formulario.listarComboEnvasePro(listae));
        cbxMarca.setModel(Formulario.listarComboMarcaPro(listama));
        cbxIva.setModel(Formulario.listarComboIva(listaIva));
         cbcCategoria.setModel(Formulario.listarComboCategoriaPro(listaca));
        txtFechaActual.setText(FechaActual());
        //  txtDescuentoVenta.setText("0");
        usuario.setText(obj.getApellidos() + " " + obj.getNombres());
        id_usuario.setText(obj.getId_sesion().toString());
        Habilitar(false);
        txtUnidades.setEnabled(true);
    }

    public void Habilitar(boolean valor) {
        ingresoDePrecio.setEnabled(valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxMarca = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbcCategoria = new javax.swing.JComboBox<>();
        btnAgregarCategoria = new javax.swing.JButton();
        btnAgreMarca = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnAgreEnvase = new javax.swing.JButton();
        cbxEnvase = new javax.swing.JComboBox<>();
        nombre1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbxIva = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtcantMinima = new javax.swing.JTextField();
        ingresoDePrecio = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cbxMedida = new javax.swing.JComboBox<>();
        btnAgregarMedida = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbxReceta = new javax.swing.JComboBox<>();
        txtPeso1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtUnidades = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        codigo2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbxTipos = new javax.swing.JComboBox<>();
        btnAgregarTipo = new javax.swing.JButton();
        usuario = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFechaActual = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        id_usuario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 99, 50), 2));
        jPanel2.setOpaque(false);

        btnAgregar.setBackground(new java.awt.Color(0, 27, 134));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 99, 50), 2));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 27, 134));
        jLabel2.setText("NOMBRE DE PRODUCTO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 27, 134));
        jLabel8.setText("MARCA/LABORATORIO:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 25));

        cbxMarca.setEditable(true);
        cbxMarca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 160, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 27, 134));
        jLabel3.setText("DESCRIPCION:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 25));

        txtDescripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 99, 50)));
        txtDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescripcionFocusLost(evt);
            }
        });
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 320, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 27, 134));
        jLabel5.setText("PRESENTACION:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 25));

        cbcCategoria.setEditable(true);
        cbcCategoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbcCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(cbcCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 160, 25));

        btnAgregarCategoria.setBackground(new java.awt.Color(0, 27, 134));
        btnAgregarCategoria.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnAgregarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCategoria.setText("AGREGAR");
        btnAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 90, 25));

        btnAgreMarca.setBackground(new java.awt.Color(0, 27, 134));
        btnAgreMarca.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnAgreMarca.setForeground(new java.awt.Color(255, 255, 255));
        btnAgreMarca.setText("AGREGAR");
        btnAgreMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgreMarcaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgreMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 90, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 27, 134));
        jLabel6.setText("PESO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 25));

        btnAgreEnvase.setBackground(new java.awt.Color(0, 27, 134));
        btnAgreEnvase.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnAgreEnvase.setForeground(new java.awt.Color(255, 255, 255));
        btnAgreEnvase.setText("AGREGAR");
        btnAgreEnvase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgreEnvaseActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgreEnvase, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 90, 25));

        cbxEnvase.setEditable(true);
        cbxEnvase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbxEnvase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEnvaseActionPerformed(evt);
            }
        });
        jPanel1.add(cbxEnvase, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 160, 25));

        nombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 99, 50)));
        nombre1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombre1FocusLost(evt);
            }
        });
        jPanel1.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 160, 25));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 27, 134));
        jLabel20.setText("IVA:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, 25));

        cbxIva.setEditable(true);
        cbxIva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbxIva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));
        cbxIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIvaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 105, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 27, 134));
        jLabel7.setText("CANT. MINIMA STOCK:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 25));

        txtcantMinima.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtcantMinima.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 99, 50)));
        txtcantMinima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantMinimaActionPerformed(evt);
            }
        });
        jPanel1.add(txtcantMinima, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 160, 25));

        ingresoDePrecio.setBackground(new java.awt.Color(0, 27, 134));
        ingresoDePrecio.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ingresoDePrecio.setForeground(new java.awt.Color(255, 255, 255));
        ingresoDePrecio.setText("INGRESAR PRECIOS");
        ingresoDePrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoDePrecioActionPerformed(evt);
            }
        });
        jPanel1.add(ingresoDePrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 138, 25));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 27, 134));
        jLabel10.setText(" MEDIDA:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, 25));

        cbxMedida.setEditable(true);
        cbxMedida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbxMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMedidaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 160, 25));

        btnAgregarMedida.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnAgregarMedida.setText("+");
        btnAgregarMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMedidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 40, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 27, 134));
        jLabel9.setText("CATEGORIA:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 25));

        cbxReceta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIN RECETA ", "CON RECETA" }));
        jPanel1.add(cbxReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));

        txtPeso1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPeso1.setText("0");
        txtPeso1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 99, 50)));
        txtPeso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeso1ActionPerformed(evt);
            }
        });
        txtPeso1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPeso1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPeso1KeyTyped(evt);
            }
        });
        jPanel1.add(txtPeso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 72, 25));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 27, 134));
        jLabel11.setText("UNIDADES:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, 25));

        txtUnidades.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUnidades.setText("1");
        txtUnidades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 99, 50)));
        txtUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadesActionPerformed(evt);
            }
        });
        txtUnidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUnidadesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUnidadesKeyTyped(evt);
            }
        });
        jPanel1.add(txtUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 220, 80, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 27, 134));
        jLabel4.setText("CODIGO DE BARRAS:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 27, 134));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 90, 30));

        codigo2.setEditable(false);
        codigo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codigo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 99, 50)));
        jPanel1.add(codigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 13, 160, 28));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 27, 134));
        jLabel13.setText("TIPO:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 25));

        cbxTipos.setEditable(true);
        cbxTipos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbxTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTiposActionPerformed(evt);
            }
        });
        jPanel1.add(cbxTipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 160, 25));

        btnAgregarTipo.setBackground(new java.awt.Color(0, 27, 134));
        btnAgregarTipo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnAgregarTipo.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarTipo.setText("AGREGAR");
        btnAgregarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTipoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 90, 25));

        usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 27, 134));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 27, 134));
        jLabel12.setText("FECHA:");

        txtFechaActual.setEditable(false);
        txtFechaActual.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFechaActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaActual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 99, 50)));

        jLabel1.setForeground(new java.awt.Color(0, 27, 134));

        id_usuario.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        id_usuario.setForeground(new java.awt.Color(0, 27, 134));

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(50, 99, 50)));
        jPanel3.setOpaque(false);

        jLabel14.setBackground(new java.awt.Color(0, 153, 153));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 27, 134));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("PRODUCTOS");
        jLabel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel14MouseDragged(evt);
            }
        });
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cerrar.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(206, 206, 206)
                .addComponent(lblCerrar)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(lblCerrar)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(id_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String valor = "";
        if (cbxIva.getSelectedIndex() == 0) {

            JOptionPane.showMessageDialog(this, "Elija Iva");
            getToolkit().beep();
        } else {
            if (!"".equals(seleccionId())) {
                JOptionPane.showMessageDialog(this, error);

            } else {

                Productos p = new Productos();
                p.setCodigo_barras(codigo2.getText());
                p.setNombre(nombre1.getText());
                p.setDescripcion(txtDescripcion.getText());
                p.setFecha_registro(Fecha.FechaSql());
                try {
                    p.setPeso(Double.parseDouble(txtPeso1.getText()));
                } catch (Exception e) {
                    p.setPeso(Double.parseDouble("0"));
                }
                p.setId_tipo(id_tipo);
                p.setId_medidas(id_medida);
                p.setId_envase(id_envase);
                p.setId_marcas(id_marca);
                p.setId_categoria(id_categoria);
             
                p.setId_usuario(Long.valueOf(id_usuario.getText()));
                p.setIva(IVA);
                try {
                    p.setCantidad_minima(Long.valueOf(txtcantMinima.getText()));
                } catch (Exception e) {
                    p.setCantidad_minima(Long.valueOf("0"));
                }
                p.setReceta(cbxReceta.getSelectedItem().toString());
                try {
                    p.setUnidades(Long.valueOf(txtUnidades.getText()));
                } catch (Exception e) {
                    p.setUnidades(Long.valueOf("1"));
                }
                valor = crud.insertarProductoNuevo(p);
                JOptionPane.showMessageDialog(this, valor);

                Productos p2 = new Productos();
                p2.setNombre(nombre1.getText());
                p2.setDescripcion(txtDescripcion.getText());
                p2.setFecha_registro(Fecha.FechaSql());
                try {
                    p2.setPeso(Double.parseDouble(txtPeso1.getText()));
                } catch (Exception e) {
                    p2.setPeso(Double.parseDouble("0"));
                }
                p2.setPeso(Double.parseDouble(txtPeso1.getText()));
                p2.setId_tipo(id_tipo);
                p2.setId_medidas(id_medida);
                p2.setId_envase(id_envase);
                p2.setId_marcas(id_marca);
                p2.setId_categoria(id_categoria);
                p2.setId_usuario(Long.valueOf(id_usuario.getText()));
                p2.setIva(IVA);
                try {
                    p2.setCantidad_minima(Long.valueOf(txtcantMinima.getText()));
                } catch (Exception e) {
                    p2.setCantidad_minima(Long.valueOf("0"));
                }
                p2.setReceta(cbxReceta.getSelectedItem().toString());
                System.out.println("Unidades 2 " + txtUnidades.getText());
                try {
                    p2.setUnidades(Long.valueOf(txtUnidades.getText()));
                } catch (Exception e) {
                    p2.setUnidades(Long.valueOf("1"));
                }

                //    p2.setDescuento_venta(Long.valueOf(txtDescuentoVenta.getText()));
                valorIDProd = crud.BuscarIDProductoNuevo(p2);
                if (valorIDProd != null) {
                    Habilitar(true);
                    btnAgregar.setEnabled(false);
                }
                //setVisible(false);
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed
    public void validar_unidades() {
        if (cbxEnvase.getSelectedItem().equals("CAJAS")) {
            txtUnidades.setEnabled(true);
        }
    }
    private void jLabel14MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseDragged

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        x = evt.getX();
        y = evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        CodigoBarras cod = new CodigoBarras(null, rootPaneCheckingEnabled);
        cod.setVisible(true);
        codigo2.setText(cod.getCodigoBarra());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUnidadesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidadesKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || Character.isSpaceChar(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtUnidadesKeyTyped

    private void txtUnidadesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnidadesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadesKeyReleased

    private void txtUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadesActionPerformed

    private void txtPeso1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPeso1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeso1KeyTyped

    private void txtPeso1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPeso1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeso1KeyReleased

    private void txtPeso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeso1ActionPerformed

    private void btnAgregarMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMedidaActionPerformed
        AgregarMedida agremed = new AgregarMedida(new javax.swing.JFrame(), true);
        agremed.setVisible(true);
        listam = crud.listarTodoMedidasProductos();//     listarTodoTipoProductos1();
        cbxMedida.setModel(Formulario.listarComboMedidaPro(listam));
    }//GEN-LAST:event_btnAgregarMedidaActionPerformed

    private void cbxMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMedidaActionPerformed
        seleccionId();
    }//GEN-LAST:event_cbxMedidaActionPerformed

    private void ingresoDePrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoDePrecioActionPerformed
         //      Ingreso_de_Precios p = new Ingreso_de_Precios(new javax.swing.JFrame(), true,Long.valueOf(valorIDProd),nombre1.getText());
        //        p.setVisible(true);
        Mantenimiento_Precios_Productos p = new Mantenimiento_Precios_Productos(new javax.swing.JFrame(), true, Long.valueOf(valorIDProd), nombre1.getText());
        p.setVisible(true);
    }//GEN-LAST:event_ingresoDePrecioActionPerformed

    private void txtcantMinimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantMinimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantMinimaActionPerformed

    private void cbxIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIvaActionPerformed
        IVA = cbxIva.getSelectedItem().toString();
        System.out.println("iba: " + IVA);
    }//GEN-LAST:event_cbxIvaActionPerformed

    private void nombre1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombre1FocusLost
        nombre1.setText(nombre1.getText().toUpperCase());
    }//GEN-LAST:event_nombre1FocusLost

    private void cbxEnvaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEnvaseActionPerformed
        seleccionId();
        validar_unidades(); // System.out.println(" " + listae.get(pos_envase).getId_envase() + " " + listae.get(pos_envase).getNombreEnvase());
    }//GEN-LAST:event_cbxEnvaseActionPerformed

    private void btnAgreEnvaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgreEnvaseActionPerformed
        AgregarEnvase agreenv = new AgregarEnvase(new javax.swing.JFrame(), true);
        agreenv.setVisible(true);
        listae = crud.listarTodoEnvaseProductos();
        cbxEnvase.setModel(Formulario.listarComboEnvasePro(listae));
    }//GEN-LAST:event_btnAgreEnvaseActionPerformed

    private void btnAgreMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgreMarcaActionPerformed
        AgregarMarca agremar = new AgregarMarca(new javax.swing.JFrame(), true);
        agremar.setVisible(true);
        listama = crud.listarTodoMarcaProductos();//     listarTodoTipoProductos1();
        cbxMarca.setModel(Formulario.listarComboMarcaPro(listama));
    }//GEN-LAST:event_btnAgreMarcaActionPerformed

    private void btnAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCategoriaActionPerformed
         AgregarCategoria nuevocategoria = new AgregarCategoria(new javax.swing.JFrame(), true);
        nuevocategoria.setVisible(true);
        listaca = crud.listarTodoCategoriaProductos();
        cbcCategoria.setModel(Formulario.listarComboCategoriaPro(listaca));
    }//GEN-LAST:event_btnAgregarCategoriaActionPerformed

    private void cbcCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcCategoriaActionPerformed
        seleccionId();
    }//GEN-LAST:event_cbcCategoriaActionPerformed

    private void txtDescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescripcionFocusLost
        txtDescripcion.setText(txtDescripcion.getText().toUpperCase());
    }//GEN-LAST:event_txtDescripcionFocusLost

    private void cbxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMarcaActionPerformed
        seleccionId();
    }//GEN-LAST:event_cbxMarcaActionPerformed

    private void cbxTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTiposActionPerformed
         seleccionId();
    }//GEN-LAST:event_cbxTiposActionPerformed

    private void btnAgregarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTipoActionPerformed
        // TODO add your handling code here:
         AgregarTipo nuevotipo = new AgregarTipo(new javax.swing.JFrame(), true);
        nuevotipo.setVisible(true);
        lista = crud.listarTodoTipoProductos1();
        cbxTipos.setModel(Formulario.listarComboTipoPro(lista));
    }//GEN-LAST:event_btnAgregarTipoActionPerformed

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        setVisible(false);
    }//GEN-LAST:event_lblCerrarMouseClicked
//    public void keyTyped(KeyEvent e) {
//        char caracter = e.getKeyChar();
//        String P = "..";
//        if (txtPeso.getText() == "") {
//            if (((caracter < '0') || (caracter > '9')) && (caracter != KeyEvent.VK_BACK_SPACE)
//                    && (caracter != '.')) {
//                e.consume();
//            }
//        }
//    }

    private String seleccionId() {
        error = "";

        if (nombre1.getText().length() < 5) {
            error = error + "\nNombre invalido!";
        }
        if (txtDescripcion.getText().length() < 5) {
            error = error + "\nDescripcion invalida!";
        }
////        if (txtDescuentoVenta.getText() == null || "".equals(txtDescuentoVenta.getText())) {
////            error = error + "\nCantidad invalida!";
////        }
        int pos = (cbxTipos.getSelectedIndex() - 1);
        if (pos < 0) {
            error = error + "\nTipo de producto invalido !";
        } else {
            id_tipo = lista.get(pos).getId_tipo();
            System.err.println(id_tipo);
        }

        pos = (cbxMedida.getSelectedIndex() - 1);
        if (pos < 0) {
            error = error + "\nMedida invalida !";
        } else {
            id_medida = listam.get(pos).getId_medidas();
            System.err.println(id_medida);
        }

        pos = (cbxMarca.getSelectedIndex() - 1);
        if (pos < 0) {
            error = error + "\nMarca invalida !";
        } else {
            id_marca = listama.get(pos).getId_Marcas();
            System.err.println(id_marca);
        }

        pos = (cbxEnvase.getSelectedIndex() - 1);
        if (pos < 0) {
            error = error + "\nEnvase invalido !";
        } else {
            id_envase = listae.get(pos).getId_presentaciones();
            System.err.println(id_envase);
        }
        
        
         pos = (cbcCategoria.getSelectedIndex() - 1);
        if (pos < 0) {
            error = error + "\nCategoria invalido !";
        } else {
            id_categoria = listaca.get(pos).getId_categoria();
            System.err.println(id_categoria);
        }
        return error;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Products dialog = new Products(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public static String FechaActual() {
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("YYYY/MM/dd");
        return formatoFecha.format(fecha);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgreEnvase;
    private javax.swing.JButton btnAgreMarca;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarCategoria;
    private javax.swing.JButton btnAgregarMedida;
    private javax.swing.JButton btnAgregarTipo;
    private javax.swing.JComboBox<String> cbcCategoria;
    private javax.swing.JComboBox<String> cbxEnvase;
    private javax.swing.JComboBox<String> cbxIva;
    private javax.swing.JComboBox<String> cbxMarca;
    private javax.swing.JComboBox<String> cbxMedida;
    private javax.swing.JComboBox<String> cbxReceta;
    private javax.swing.JComboBox<String> cbxTipos;
    public javax.swing.JTextField codigo2;
    private javax.swing.JLabel id_usuario;
    private javax.swing.JButton ingresoDePrecio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public static javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JTextField nombre1;
    public static javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFechaActual;
    public static javax.swing.JTextField txtPeso1;
    private javax.swing.JTextField txtUnidades;
    public static javax.swing.JTextField txtcantMinima;
    public static javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
