/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.farmacia.views.ventas;

import com.farmacia.conponentes.Tablas;
import com.farmacia.dao.CRUD;
import com.farmacia.entities1.Cabecera_ventas;
import com.farmacia.entities1.Detalle_ventas;
import com.farmacia.entities1.Calcular_totales;
import com.farmacia.entities1.ClaseReporte;
import com.farmacia.entities1.Listar_usuario;
import com.farmacia.entities1.Persona;
import com.farmacia.entities1.StockVentas;
import com.farmacia.join_entidades.JoinListarProductosVentas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Label;
import java.awt.MouseInfo;
import java.awt.Point;
import java.io.InputStream;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

public class MenuPreVentas extends javax.swing.JDialog {

    String ImagenLogo = System.getProperty("user.dir") + "/src/com/farmacia/imagenes/" + "logoasofar.jpg";
    int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
    int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
    ArrayList<Detalle_ventas> ListarDetalle = new ArrayList<Detalle_ventas>();
    ArrayList<Persona> listaCliente = null;
    ArrayList<StockVentas> listaStockVentas = null;

    Listar_usuario objUsuario = null;
    // Label jlId_pro = new ConsultarProductoVentas().lblId.getText();
    CRUD crud = new CRUD();
    JoinListarProductosVentas objProd = new JoinListarProductosVentas();
    Persona objCliente = new Persona();
    Persona objClienteC = new Persona();
    Persona objClienteC1 = new Persona();
    Calcular_totales ct = new Calcular_totales();
    int x, y;
    Cabecera_ventas objeto = new Cabecera_ventas();
    Detalle_ventas objeto1 = new Detalle_ventas();
    int dia, mes, ano;
    Calendar c1 = Calendar.getInstance();

    public MenuPreVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listaCliente = crud.ListarTodoClienteVentas("1");
        getContentPane().setBackground(Color.white);
//        TxtCedula.setText("9999999999");
//        TxtNombre.setText("CONSUMIDOR FINAL");
//        TxtCorreo.setText("*************************************");
//        TxtDirec.setText("*************************************");
//        TxtTelefono.setText("*************************************");
        this.setLocationRelativeTo(null);

        TxtProdNombre.setEnabled(false);
        TxtProdPrecio.setEnabled(false);
        TxtProdCantidad.setEnabled(false);
        TxtProdSubtotal.setEnabled(false);
        TxtDescuentoPorcentaje.setEnabled(false);
        TxtProdDescuento.setEnabled(false);
        TxtProdIva.setEnabled(false);
        TxtProdtotal.setEnabled(false);

    }

    public MenuPreVentas(java.awt.Frame parent, boolean modal, Listar_usuario objlogin) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.white);
//        TxtCedula.setText("9999999999");
//        TxtNombre.setText("CONSUMIDOR FINAL");
//        TxtCorreo.setText("*************************************");
//        TxtDirec.setText("*************************************");
//        TxtTelefono.setText("*************************************");
        BtnGenerarVenta.setEnabled(false);
        this.setLocationRelativeTo(null);
        listaCliente = crud.ListarTodoClienteVentas("1");
        objUsuario = objlogin;
        TxtProdNombre.setEnabled(false);
        TxtProdPrecio.setEnabled(false);
        TxtProdCantidad.setEnabled(false);
        TxtProdSubtotal.setEnabled(false);
        TxtDescuentoPorcentaje.setEnabled(false);
        TxtProdDescuento.setEnabled(false);
        TxtProdIva.setEnabled(false);
        TxtProdtotal.setEnabled(false);
        BtnAddIten.setEnabled(false);

    }

    public MenuPreVentas() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TxtCedula = new javax.swing.JTextField();
        BtnBuscarcedula = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtDirec = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        TxtCorreo = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        CbxFormaPago = new javax.swing.JComboBox<>();
        CbxTipoVenta = new javax.swing.JComboBox<>();
        BtnGenerarVenta = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        TxtSubtotalconIva = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        TxtDescuento = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        TxtIva = new javax.swing.JTextField();
        TxtTotal = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TxtProdNombre = new javax.swing.JTextField();
        BtnBuscarprodnombre = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TxtProdCantidad = new javax.swing.JTextField();
        TxtProdSubtotal = new javax.swing.JTextField();
        TxtProdIva = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtProdPrecio = new javax.swing.JTextField();
        TxtProdtotal = new javax.swing.JTextField();
        BtnAddIten = new javax.swing.JButton();
        TxtProdDescuento = new javax.swing.JTextField();
        TxtDescuentoPorcentaje = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TxtSubtotalsinIva = new javax.swing.JTextField();
        TxtSubtotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaListarVentas = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 99, 50), 2, true));
        jPanel6.setOpaque(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 99, 50), 2, true), "DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 27, 134))); // NOI18N
        jPanel1.setOpaque(false);

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 99, 50), 2, true));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 27, 134));
        jLabel3.setText("CEDULA/RUC:");

        TxtCedula.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        BtnBuscarcedula.setBackground(new java.awt.Color(0, 27, 134));
        BtnBuscarcedula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnBuscarcedula.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscarcedula.setText("BUSCAR");
        BtnBuscarcedula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBuscarcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarcedulaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 27, 134));
        jLabel7.setText("NOMBRE:");

        TxtNombre.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 27, 134));
        jLabel8.setText("DIRECCION:");

        TxtDirec.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 27, 134));
        jLabel4.setText("TELEFONO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 27, 134));
        jLabel5.setText("CORREO:");

        TxtTelefono.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        TxtCorreo.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 27, 134));
        jCheckBox1.setText("CONSUMIDOR FINAL");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(TxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBuscarcedula))
                    .addComponent(TxtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCheckBox1)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CbxFormaPago.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        CbxFormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "contado", "credito" }));

        CbxTipoVenta.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        CbxTipoVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Factura", "Nota de venta" }));

        BtnGenerarVenta.setBackground(new java.awt.Color(0, 27, 134));
        BtnGenerarVenta.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        BtnGenerarVenta.setForeground(new java.awt.Color(255, 255, 255));
        BtnGenerarVenta.setText("GENERAR VENTA");
        BtnGenerarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnGenerarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CbxTipoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbxFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(CbxTipoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(BtnGenerarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(CbxFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 99, 50), 2, true), "DETALLE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 27, 134))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 27, 134));
        jLabel25.setText("IVA:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 27, 134));
        jLabel22.setText("SUBTOTAL CON 12%:");

        TxtSubtotalconIva.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 27, 134));
        jLabel23.setText("TOTAL:");

        TxtDescuento.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 27, 134));
        jLabel24.setText("DESCUENTO:");

        TxtIva.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        TxtTotal.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 99, 50), 2, true)));

        TxtProdNombre.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        BtnBuscarprodnombre.setBackground(new java.awt.Color(0, 27, 134));
        BtnBuscarprodnombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnBuscarprodnombre.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscarprodnombre.setText("BUSCAR");
        BtnBuscarprodnombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBuscarprodnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarprodnombreActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 27, 134));
        jLabel13.setText("PRODUCTO:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 27, 134));
        jLabel16.setText("CANTIDAD:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 27, 134));
        jLabel17.setText("SUBTOTAL:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 27, 134));
        jLabel18.setText("PRECIO FINAL:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 27, 134));
        jLabel19.setText("IVA:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 27, 134));
        jLabel20.setText("DESCUENTO:");

        TxtProdCantidad.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        TxtProdCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtProdCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtProdCantidadKeyTyped(evt);
            }
        });

        TxtProdSubtotal.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        TxtProdIva.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 27, 134));
        jLabel14.setText("PRECIO:");

        TxtProdPrecio.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        TxtProdtotal.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        BtnAddIten.setBackground(new java.awt.Color(0, 27, 134));
        BtnAddIten.setFont(new java.awt.Font("Ubuntu", 1, 11)); // NOI18N
        BtnAddIten.setForeground(new java.awt.Color(255, 255, 255));
        BtnAddIten.setText("ADICIONAR ITEM");
        BtnAddIten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddItenActionPerformed(evt);
            }
        });

        TxtProdDescuento.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        TxtDescuentoPorcentaje.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        TxtDescuentoPorcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtDescuentoPorcentajeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDescuentoPorcentajeKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 27, 134));
        jLabel1.setText("%DESCUENTO:");

        jButton2.setBackground(new java.awt.Color(0, 27, 134));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDITAR");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel16)
                                            .addGap(286, 286, 286))
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(257, 257, 257)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtProdIva, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtProdDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtProdtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtProdSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtProdCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtProdPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtProdNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(TxtDescuentoPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton2))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(BtnAddIten)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnBuscarprodnombre)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtProdNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarprodnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtProdPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtProdCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtProdSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtDescuentoPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtProdDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtProdIva, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtProdtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAddIten, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 27, 134));
        jLabel26.setText("SUBTOTAL CON 0%:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 27, 134));
        jLabel27.setText("SUBTOTAL SIN IMPUESTO:");

        TxtSubtotalsinIva.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        TxtSubtotal.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 99, 50), 2));

        TablaListarVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaListarVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaListarVentasMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(TablaListarVentas);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtSubtotalconIva, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtSubtotalsinIva, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(TxtSubtotalconIva, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(TxtSubtotalsinIva, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(jLabel28)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(50, 99, 50)));
        jPanel7.setOpaque(false);

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 27, 134));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VENTAS");
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/cerrar.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(467, 467, 467)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCerrar)
                .addGap(23, 23, 23))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblCerrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Persona devuelveObjeto(String datos, ArrayList<Persona> listarobj) {
        Persona objeto1 = null;
        for (int i = 0; i < listarobj.size(); i++) {
            System.out.println("id " + datos);
            if (datos.equals(listarobj.get(i).getId_Clientes().toString())) {

                objeto1 = listarobj.get(i);

                break;
            }
        }
        return objeto1;
    }

    public Persona getCliente1() {
        objClienteC = devuelveObjeto(String.valueOf(10), listaCliente);
        return objClienteC;
    }


    private void BtnBuscarcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarcedulaActionPerformed

        ConsultarClienteVentas cc = new ConsultarClienteVentas(new javax.swing.JFrame(), true);
        cc.setVisible(true);
        objCliente = cc.getCliente();
        if (objCliente != null) {

            TxtCedula.setText(objCliente.getCedula());
            TxtNombre.setText(objCliente.getNombre() + " " + objCliente.getApellido());
            TxtDirec.setText(objCliente.getDireccion());
            TxtTelefono.setText(objCliente.getStr_telefono());
            TxtCorreo.setText(objCliente.getStr_correo());

        }
    }//GEN-LAST:event_BtnBuscarcedulaActionPerformed

    private void BtnGenerarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerarVentaActionPerformed

        if (!TxtTotal.getText().equals("") && !TxtCedula.getText().equals("")) {

            if (!jCheckBox1.isSelected()) {

                Cabecera_ventas cv = new Cabecera_ventas();

                String id_cab;
                int can;
                String query = "SELECT COUNT(*)+1 AS 'cantidad' FROM cabecera_venta";
                can = crud.obtenerNumeroOrdenes(query);

                cv.setMun_venta(String.format("%06d", can));

                cv.setId_cliente(objCliente.getId_Clientes());

                cv.setId_usuario(Long.parseLong("36"));
                cv.setId_usuario(objUsuario.getId_sesion());
                cv.setId_sucursal(Long.parseLong("2"));
                cv.setForma_de_pago(CbxFormaPago.getSelectedItem().toString());
                cv.setTipo_de_venta(CbxTipoVenta.getSelectedItem().toString());

                cv.setSubtotal_con_iva(ct.getSubtotalConIva());
                cv.setSubtotal_sin_iva(ct.getSubtotalSinIva());
                cv.setSubtotal_venta(ct.getSubtotal());
                cv.setDescuento_venta(ct.getDescuento());
                cv.setIva_venta(ct.getIva());
                cv.setTotal_venta(ct.getTotal());
                cv.setUtilidad(ct.getUtilidad());
                cv.setEstado("A");

                id_cab = crud.InsertarCabeceraVentas(cv);
                cv.setId_cabecera_venta(Long.parseLong(id_cab));

                objeto = cv;

                for (int i = 0; i < ListarDetalle.size(); i++) {

                    Detalle_ventas dv = new Detalle_ventas();
                    String id_det;

                    dv.setId_cabecera_venta(cv.getId_cabecera_venta());
                    dv.setId_control(ListarDetalle.get(i).getId_control());
                    dv.setPrecio(ListarDetalle.get(i).getPrecio());
                    if (ListarDetalle.get(i).getEmpaque() == 1) {
                        dv.setMarca(ListarDetalle.get(i).getMarca());

                        dv.setCantidad(ListarDetalle.get(i).getCantidad());
                        dv.setCantidad_unidad(Long.valueOf(0));
                    } else {
                        dv.setCantidad(Long.valueOf(0));
                        dv.setCantidad_unidad(ListarDetalle.get(i).getCantidad());
                    }
                    dv.setIva(ListarDetalle.get(i).getIva());
                    dv.setDescuento(ListarDetalle.get(i).getDescuento());

                    id_det = crud.InsertarDetalleVentas(dv);
                    dv.setId_cabecera_venta(Long.parseLong(id_det));

                }
                listaStockVentas = crud.listarStockVentas(Long.parseLong(id_cab));

                for (int i = 0; i < listaStockVentas.size(); i++) {
                    System.out.println("id control " + listaStockVentas.get(i).getId_control());
                    System.out.println("cantidad " + listaStockVentas.get(i).getCantidad());

                    crud.ActulizarStockVentas(listaStockVentas.get(i));
                    //crud.insertarKardex_ventas();
                }
                reporteJasper();
                reiniciar();
//                this.setVisible(false);
//                ImprimirOrdenVentas ov = new ImprimirOrdenVentas(new javax.swing.JFrame(), true, objeto);
//                ov.setVisible(true);
            } else if (jCheckBox1.isEnabled()) {

                objClienteC1 = getCliente1();
                Cabecera_ventas cv = new Cabecera_ventas();

                String id_cab;
                int can;
                String query = "SELECT COUNT(*)+1 AS 'cantidad' FROM cabecera_venta";
                can = crud.obtenerNumeroOrdenes(query);

                cv.setMun_venta(String.format("%06d", can));

                cv.setId_cliente(objClienteC1.getId_Clientes());

                cv.setId_usuario(Long.parseLong("36"));
                cv.setId_usuario(objUsuario.getId_sesion());
//            System.out.println("usuario :" + objUsuario.getApellidos());
                cv.setId_sucursal(Long.parseLong("2"));
                cv.setForma_de_pago(CbxFormaPago.getSelectedItem().toString());
                cv.setTipo_de_venta(CbxTipoVenta.getSelectedItem().toString());
                cv.setSubtotal_con_iva(ct.getSubtotalConIva());
                cv.setSubtotal_sin_iva(ct.getSubtotalSinIva());
                cv.setSubtotal_venta(ct.getSubtotal());
                cv.setDescuento_venta(ct.getDescuento());
                cv.setIva_venta(ct.getIva());
                cv.setTotal_venta(ct.getTotal());
                cv.setUtilidad(ct.getUtilidad());
                cv.setEstado("A");

                id_cab = crud.InsertarCabeceraVentas(cv);
                cv.setId_cabecera_venta(Long.parseLong(id_cab));

                objeto = cv;

                for (int i = 0; i < ListarDetalle.size(); i++) {

                    Detalle_ventas dv = new Detalle_ventas();
                    String id_det;

                    dv.setId_cabecera_venta(cv.getId_cabecera_venta());
                    dv.setId_control(ListarDetalle.get(i).getId_control());
                    dv.setPrecio(ListarDetalle.get(i).getPrecio());
                    if (ListarDetalle.get(i).getEmpaque() == 1) {
                        dv.setCantidad(ListarDetalle.get(i).getCantidad());
                        dv.setCantidad_unidad(Long.valueOf(0));
                    } else {
                        dv.setCantidad(Long.valueOf(0));
                        dv.setCantidad_unidad(ListarDetalle.get(i).getCantidad());
                    }
                    dv.setIva(ListarDetalle.get(i).getIva());
                    dv.setDescuento(ListarDetalle.get(i).getDescuento());

                    id_det = crud.InsertarDetalleVentas(dv);
                    dv.setId_cabecera_venta(Long.parseLong(id_det));

                }
                listaStockVentas = crud.listarStockVentas(Long.parseLong(id_cab));

                for (int i = 0; i < listaStockVentas.size(); i++) {
                    System.out.println("id control " + listaStockVentas.get(i).getId_control());
                    System.out.println("cantidad " + listaStockVentas.get(i).getCantidad());

                    crud.ActulizarStockVentas(listaStockVentas.get(i));
                    //crud.insertarKardex_ventas();
                }
                reporteJasper();
                reiniciar();
//                this.setVisible(false);
//                ImprimirOrdenVentas ov = new ImprimirOrdenVentas(new javax.swing.JFrame(), true, objeto);
//                ov.setVisible(true);
            }
        }


    }//GEN-LAST:event_BtnGenerarVentaActionPerformed

    public Cabecera_ventas getCabecera() {
        return objeto;

    }

    public void reporteJasper() {
        Cabecera_ventas cv = new Cabecera_ventas();
        ArrayList lista = new ArrayList();
        dia = (c1.get(Calendar.DATE));
        mes = (c1.get(Calendar.MONTH)) + 1;
        ano = (c1.get(Calendar.YEAR));
        String fecha = (dia + "-" + mes + "-" + ano);
//        String dir = System.getProperty("user.dir") + "\\P_Farmacia00_Menu3.jar";
        for (int i = 0; i < TablaListarVentas.getRowCount(); i++) {
            ClaseReporte creporte = new ClaseReporte(
                    String.valueOf(objeto.getMun_venta()),
                    TxtNombre.getText(),
                    fecha,
                    fecha,
                    TablaListarVentas.getValueAt(i, 0).toString(),
                    TablaListarVentas.getValueAt(i, 3).toString(),
                    TablaListarVentas.getValueAt(i, 5).toString(),
                    TablaListarVentas.getValueAt(i, 6).toString(),
                    TablaListarVentas.getValueAt(i, 7).toString(),
                    TablaListarVentas.getValueAt(i, 9).toString(),
                    TablaListarVentas.getValueAt(i, 10).toString(),
                    TablaListarVentas.getValueAt(i, 11).toString(),
                    TxtSubtotalconIva.getText(),
                    TxtSubtotalsinIva.getText(),
                    TxtSubtotal.getText(),
                    TxtDescuento.getText(),
                    TxtIva.getText(),
                    TxtTotal.getText(),
                    TablaListarVentas.getValueAt(i, 8).toString());
            lista.add(creporte);
        }

        try {
//            Map parametro = new HashMap();
//            parametro.put("conte", String.valueOf(dir));
            JasperReport report = (JasperReport) JRLoader.loadObject(getClass().getResource("Venta.jasper"));
//            InputStream report = MenuPreVentas.class.getResourceAsStream("Venta.jasper");
//            String dir = System.getProperty("user.dir") + "/Reportes/" +"Venta.jasper";
//            InputStream report = JRLoader.getFileInputStream("Venta.jasper");
            JasperPrint jprint = JasperFillManager.fillReport(report, null, new JRBeanCollectionDataSource(lista));
            JDialog frame = new JDialog(this);
            JRViewer viewer = new JRViewer(jprint);
//            JasperViewer viewer = new JasperViewer(jprint, false);
            frame.add(viewer);
            frame.setSize(new Dimension(ancho / 2, alto / 2));
            frame.setLocationRelativeTo(null);
//            viewer.setLocationRelativeTo(null);
            frame.setVisible(true);
//            viewer.setVisible(true);
            viewer.setFitWidthZoomRatio();
            /*
             InputStream reporteInputStream = MiClase.class.getResourceAsStream("/reportes/" + archivo);
             JasperPrint jasperPrint = JasperFillManager.fillReport(reporteInputStream, null, conexion);
             JasperViewer jView = new JasperViewer(jasperPrint, false);
             jView.setVisible(true);
             */
        } catch (JRException ex) {
            
            JOptionPane.showMessageDialog(rootPane, "report fail: " + ex);
            Logger.getLogger(MenuPreVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void BtnAddItenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddItenActionPerformed

        if (TxtProdNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "ELIJA UN PRODUCTO");
        } else {
            if (objProd.getStock() < Long.valueOf(TxtProdCantidad.getText())) {
                String msg = "Stock disponible: " + objProd.getStock();

                JOptionPane.showMessageDialog(rootPane, msg);
            } else {
                //JOptionPane.showMessageDialog(this,""+objProd.getEmpaque());  //<---
                System.out.println(" se repite  " + verificarObjeto(objProd.getId_producto().toString(), objProd.getId_precio().toString(), objProd.getEmpaque() + ""));
                if (verificarObjeto(objProd.getId_producto().toString(), objProd.getId_precio().toString(), objProd.getEmpaque() + "").equals("si")) {

                    JOptionPane.showMessageDialog(rootPane, "SE REPITE EL ITEM");
                } else {
                    Detalle_ventas RegDetalleVentas = new Detalle_ventas();

                    RegDetalleVentas.setId_control(objProd.getId_precio());//nuevo
                    RegDetalleVentas.setId_producto(objProd.getId_producto());
                    RegDetalleVentas.setCodigo_barras(Long.parseLong(objProd.getCodigo_barras()));
                    RegDetalleVentas.setNombre_producto(objProd.getProducto_nombre());
                    RegDetalleVentas.setMarca(objProd.getMarca_nombre());
                    RegDetalleVentas.setPresentacion(objProd.getPresentacion());
                    RegDetalleVentas.setTipo(objProd.getTipo_nombre());
                    RegDetalleVentas.setCantidad(Long.parseLong(TxtProdCantidad.getText()));
                    RegDetalleVentas.setPrecio(objProd.getPrecio_venta());
                    RegDetalleVentas.setPrecio_compra(objProd.getPrecio_compra());
                    RegDetalleVentas.setSubtotal(objeto1.getSubtotal());
                    RegDetalleVentas.setDescuento(objeto1.getDescuento());
                    RegDetalleVentas.setIva(objeto1.getIva());
                    RegDetalleVentas.setTotal(objeto1.getTotal());
                    RegDetalleVentas.setEmpaque(objProd.getEmpaque());
                    //JOptionPane.showMessageDialog(this,""+objProd.getEmpaque());  //<---

                    ListarDetalle.add(RegDetalleVentas);

                    for (int i = 0; i < ListarDetalle.size(); i++) {
                        System.out.println(ListarDetalle.get(i).getNombre_producto());
                    }
                    Tablas.cargarListaVentasDetalle(TablaListarVentas, ListarDetalle);

                    TxtProdNombre.setText("");
                    TxtProdPrecio.setText("");
                    TxtProdCantidad.setText("");
                    TxtProdPrecio.setText("");
                    TxtProdSubtotal.setText("");
                    TxtDescuentoPorcentaje.setText("");
                    TxtProdDescuento.setText("");
                    TxtProdIva.setText("");
                    TxtProdtotal.setText("");
                    TxtProdNombre.setEnabled(false);
                    TxtProdPrecio.setEnabled(false);
                    TxtProdCantidad.setEnabled(false);
                    TxtProdSubtotal.setEnabled(false);
                    TxtDescuentoPorcentaje.setEnabled(false);
                    TxtProdDescuento.setEnabled(false);
                    TxtProdIva.setEnabled(false);
                    TxtProdtotal.setEnabled(false);

                    CalcularDetalle();

                }
            }
            BtnGenerarVenta.setEnabled(true);
        }
    }//GEN-LAST:event_BtnAddItenActionPerformed

    private void reiniciar() {
        TxtSubtotalconIva.setText("");
        TxtSubtotalsinIva.setText("");
        TxtSubtotal.setText("");
        TxtDescuento.setText("");
        TxtIva.setText("");
        TxtTotal.setText("");
        TxtCedula.setText("");
        TxtNombre.setText("");
        TxtDirec.setText("");
        TxtTelefono.setText("");
        TxtCorreo.setText("");
        TxtProdNombre.setText("");
        TxtProdPrecio.setText("");
        TxtProdCantidad.setText("");
        TxtProdPrecio.setText("");
        TxtProdSubtotal.setText("");
        TxtDescuentoPorcentaje.setText("");
        TxtProdDescuento.setText("");
        TxtProdIva.setText("");
        TxtProdtotal.setText("");
        TxtProdNombre.setEnabled(false);
        TxtProdPrecio.setEnabled(false);
        TxtProdCantidad.setEnabled(false);
        TxtProdSubtotal.setEnabled(false);
        TxtDescuentoPorcentaje.setEnabled(false);
        TxtProdDescuento.setEnabled(false);
        TxtProdIva.setEnabled(false);
        TxtProdtotal.setEnabled(false);
        TablaListarVentas.clearSelection();
        ListarDetalle.clear();
        jCheckBox1.setSelected(false);
//        listaStockVentas.clear();
//        listaCliente.clear();
        Tablas.cargarListaVentasDetalle(TablaListarVentas, ListarDetalle);
    }

    public String verificarObjeto(String datos, String idPre, String empaque) {
        String idproducto, idprecio;
        String objeto1 = "no";

        for (int i = 0; i < ListarDetalle.size(); i++) {
            idproducto = ListarDetalle.get(i).getId_producto().toString();
            idprecio = ListarDetalle.get(i).getId_control().toString();
            System.out.println("idproducto: " + datos + "-" + idproducto);
            System.out.println("idprecio: " + idPre + "-" + idprecio);

            if (datos.equals(ListarDetalle.get(i).getId_producto().toString())
                    & idPre.equals(ListarDetalle.get(i).getId_control().toString())
                    & empaque.equals(ListarDetalle.get(i).getEmpaque() + "")) {
                objeto1 = "si";
                break;
            } else {
                objeto1 = "no";
            }
        }
        return objeto1;
    }


    private void TxtProdCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtProdCantidadKeyTyped
        char car = evt.getKeyChar();
        if (car < '0' || car > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_TxtProdCantidadKeyTyped

    private void TxtProdCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtProdCantidadKeyReleased

        String query = " SELECT iva.iva AS 'iva' FROM iva WHERE iva.est  = 'A' ";

        Double iva_valor = crud.obtenerIvaVentas(query);

        BigDecimal iva = new BigDecimal("0.00");

        if (TxtProdCantidad.equals(" ") == false && TxtProdCantidad.getText().matches("[0-9]+[0-9]*")) {

            if (objProd.getStock() < Long.valueOf(TxtProdCantidad.getText())) {

                String msg = "Stock disponible: " + objProd.getStock();

                JOptionPane.showMessageDialog(rootPane, msg);

            } else {

                BigDecimal cantidad = new BigDecimal(TxtProdCantidad.getText());

                BigDecimal precio = objProd.getPrecio_venta();

                BigDecimal subtotal = cantidad.multiply(precio);

                TxtProdSubtotal.setText(subtotal.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());

                if (objProd.getIva().equals("0.12")) {

                    BigDecimal iva_val = new BigDecimal(iva_valor);
                    iva = iva_val.multiply(subtotal);

                    TxtProdIva.setText(iva.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());
                }

                if (objProd.getIva().equals("NO")) {

                    iva = BigDecimal.valueOf(00.00);

                    TxtProdIva.setText(iva.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());
                }
                BigDecimal total = subtotal.add(iva);

                TxtProdtotal.setText(total.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());

                objeto1.setSubtotal(subtotal);
                objeto1.setDescuento(BigDecimal.valueOf(0.00));
                objeto1.setIva(iva);
                objeto1.setTotal(total);

                TxtDescuentoPorcentaje.setEnabled(true);
                TxtDescuentoPorcentaje.setText("0");
                TxtProdDescuento.setText("0.00");

                System.out.println(" descuento  0");

            }

        }


    }//GEN-LAST:event_TxtProdCantidadKeyReleased
    public void CalcularDetalle() {

        String query = " SELECT iva.iva AS 'iva' FROM iva WHERE iva.est  = 'A' ";

        Double ivaVentas = crud.obtenerIvaVentas(query);

        BigDecimal TotalSubConIva = new BigDecimal("0.00");
        BigDecimal TotalSubSinIva = new BigDecimal("0.00");
        BigDecimal TotalSubTotal = new BigDecimal("0.00");
        BigDecimal TotalIva = new BigDecimal("0.00");
        BigDecimal TotalDescuento = new BigDecimal("0.00");
        BigDecimal Total = new BigDecimal("0.00");

        BigDecimal TotalSubConIvaCompra = new BigDecimal("0.00");
        BigDecimal TotalSubSinIvaCompra = new BigDecimal("0.00");
        BigDecimal TotalIvaCompra = new BigDecimal("0.00");
        BigDecimal TotalCompra = new BigDecimal("0.00");
        BigDecimal TotalSubTotalCompra = new BigDecimal("0.00");

        BigDecimal Utilidad = new BigDecimal("0.00");

        BigDecimal Iva = new BigDecimal(ivaVentas);

        for (int i = 0; i < TablaListarVentas.getRowCount(); i++) {

            Long Cant = ListarDetalle.get(i).getCantidad();
            BigDecimal Cantidad = new BigDecimal(Cant);
            System.out.println("cantidad " + Cantidad);
            BigDecimal Precio = ListarDetalle.get(i).getPrecio();
            System.out.println("Precio " + Precio);
            BigDecimal PrecioCompra = ListarDetalle.get(i).getPrecio_compra();
            System.out.println("precio compra  " + PrecioCompra);
            BigDecimal Subtotal = Cantidad.multiply(Precio);
            System.out.println("Subtotal " + Subtotal);
            BigDecimal SubtotalCompra = Cantidad.multiply(PrecioCompra);
            System.out.println("Subtotal compra " + SubtotalCompra);
            BigDecimal Descuento = ListarDetalle.get(i).getDescuento();
            System.out.println("descuento venta " + Descuento);
            TotalDescuento = TotalDescuento.add(Descuento);

            TxtSubtotalconIva.setText("0.00");
            TxtSubtotalsinIva.setText("0.00");//
            // cambio

            if ("0.00".equals(ListarDetalle.get(i).getIva().toEngineeringString()) || "0.0".equals(ListarDetalle.get(i).getIva().toEngineeringString())) {

                TotalSubSinIva = TotalSubSinIva.add(Subtotal);
                System.out.println("TotalSub SinIva " + TotalSubSinIva);
                TotalSubSinIvaCompra = TotalSubSinIvaCompra.add(SubtotalCompra);
                System.out.println("TotalSubCompra SinIva " + TotalSubSinIvaCompra);
                Iva = BigDecimal.valueOf(0.00);

            } else {

                TotalIva = TotalIva.add(Subtotal.multiply(Iva));
                System.out.println("total iva " + TotalIva);
                TotalIvaCompra = TotalIvaCompra.add(SubtotalCompra.multiply(Iva));
                System.out.println("total iva Compra " + TotalIvaCompra);

                TotalSubConIva = TotalSubConIva.add(Subtotal);
                System.out.println("subtotal con iva " + TotalSubConIva);
                TotalSubConIvaCompra = TotalSubConIvaCompra.add(SubtotalCompra);
                System.out.println("subtotalCompra con_iva " + TotalSubConIvaCompra);

            }

            Total = Total.add(Subtotal.add(Subtotal.multiply(Iva)).subtract(Descuento));
            TotalCompra = TotalCompra.add(SubtotalCompra.add(SubtotalCompra.multiply(Iva)));

            System.out.println("total venta " + Total);
            System.out.println("total compra " + TotalCompra);

        }

        TotalSubTotal = TotalSubConIva.add(TotalSubSinIva);
        TotalSubTotalCompra = TotalSubConIvaCompra.add(TotalSubSinIvaCompra);

        Utilidad = Total.subtract(TotalCompra);
        System.out.println("utilidad " + Utilidad);

        ct.setSubtotalConIva(TotalSubConIva);
        ct.setSubtotalSinIva(TotalSubSinIva);
        ct.setSubtotal(TotalSubTotal);
        ct.setIva(TotalIva);
        ct.setDescuento(TotalDescuento);
        ct.setTotal(Total);
        ct.setUtilidad(Utilidad);
        TxtSubtotalconIva.setText(TotalSubConIva.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());
        TxtSubtotalsinIva.setText(TotalSubSinIva.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());
        TxtSubtotal.setText(TotalSubTotal.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());
        TxtIva.setText(TotalIva.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());
        TxtDescuento.setText(TotalDescuento.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());
        TxtTotal.setText(Total.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());

    }


    private void BtnBuscarprodnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarprodnombreActionPerformed
        TxtProdNombre.setText("");
        TxtProdPrecio.setText("");
        TxtProdCantidad.setText("");
        TxtProdPrecio.setText("");
        TxtProdSubtotal.setText("");
        TxtDescuentoPorcentaje.setText("");
        TxtProdDescuento.setText("");
        TxtProdIva.setText("");
        TxtProdtotal.setText("");
        TxtProdNombre.setEnabled(true);
        TxtProdPrecio.setEnabled(true);
        TxtProdCantidad.setEnabled(true);
        TxtProdSubtotal.setEnabled(true);
        TxtDescuentoPorcentaje.setEnabled(true);
        TxtProdDescuento.setEnabled(true);
        TxtProdIva.setEnabled(true);
        TxtProdtotal.setEnabled(true);
        TxtProdNombre.setEditable(false);
        TxtProdPrecio.setEditable(false);
        TxtProdCantidad.setEditable(true);
        TxtProdSubtotal.setEditable(false);
        TxtDescuentoPorcentaje.setEditable(false);
        TxtProdDescuento.setEditable(false);
        TxtProdIva.setEditable(false);
        TxtProdtotal.setEditable(false);
        objProd = null;
        ConsultarProductoVentas cp = new ConsultarProductoVentas(new javax.swing.JFrame(), true);
        cp.setVisible(true);
        objProd = cp.getProducto();
        if (objProd != null) {
            TxtProdNombre.setText(objProd.getProducto_nombre());
            if (objProd.getPrecio_venta() == null) {
                TxtProdPrecio.setText("");
            } else {
                TxtProdPrecio.setText(objProd.getPrecio_venta().setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());
            }
            if (objProd.getDescuento() == null) {
                TxtDescuentoPorcentaje.setText("");
            } else {
                TxtDescuentoPorcentaje.setText(objProd.getDescuento().toString());
            }

        }
        BtnAddIten.setEnabled(true);

    }//GEN-LAST:event_BtnBuscarprodnombreActionPerformed

    private void TablaListarVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaListarVentasMousePressed

        try {

            if (evt.getClickCount() == 2) {
                int r = JOptionPane.showConfirmDialog(null, "¿Desea eliminar este producto de la lista?", "", JOptionPane.YES_NO_OPTION);
                if (r == JOptionPane.YES_OPTION) {
                    int i = TablaListarVentas.getSelectedRow();

                    ListarDetalle.remove(i);
                }

            }

            Tablas.cargarListaVentasDetalle(TablaListarVentas, ListarDetalle);
            CalcularDetalle();
            TxtProdNombre.setText("");
            TxtProdPrecio.setText("");
            TxtProdCantidad.setText("");
            TxtProdPrecio.setText("");
            TxtProdSubtotal.setText("");
            TxtProdDescuento.setText("");
            TxtProdIva.setText("");
            TxtProdtotal.setText("");
            TxtDescuentoPorcentaje.setText("");
            TxtDescuentoPorcentaje.setEnabled(false);

        } catch (Exception e) {
        }

    }//GEN-LAST:event_TablaListarVentasMousePressed

    private void TxtDescuentoPorcentajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDescuentoPorcentajeKeyTyped

        char car = evt.getKeyChar();
        if (car < '0' || car > '9') {
            evt.consume();
        }


    }//GEN-LAST:event_TxtDescuentoPorcentajeKeyTyped

    private void TxtDescuentoPorcentajeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDescuentoPorcentajeKeyReleased
        String query = " SELECT iva.iva AS 'iva' FROM iva WHERE iva.est  = 'A' ";

        Double iva_valor = crud.obtenerIvaVentas(query);

        BigDecimal iva = new BigDecimal("0.00");

        if (TxtDescuentoPorcentaje.equals(" ") == false && TxtDescuentoPorcentaje.getText().matches("[0-9]+[0-9]*")) {

            BigDecimal base = new BigDecimal(TxtProdSubtotal.getText());
            BigDecimal pct = new BigDecimal(TxtDescuentoPorcentaje.getText());
            BigDecimal porcentaje = base.multiply(pct).divide(new BigDecimal(100));

            TxtProdDescuento.setText(porcentaje.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());

            BigDecimal cantidad = new BigDecimal(TxtProdCantidad.getText());

            BigDecimal precio = objProd.getPrecio_venta();

            BigDecimal subtotal = cantidad.multiply(precio);

            TxtProdSubtotal.setText(subtotal.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());

            if (objProd.getIva().equals("0.12")) {

                BigDecimal iva_val = new BigDecimal(iva_valor);
                iva = iva_val.multiply(subtotal);

                TxtProdIva.setText(iva.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());
            }

            if (objProd.getIva().equals("NO")) {

                iva = BigDecimal.valueOf(00.00);

                TxtProdIva.setText(iva.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());
            }
            BigDecimal total = subtotal.add(iva);

            BigDecimal TotalnenosDescuento = (total.subtract(porcentaje));

            TxtProdtotal.setText(TotalnenosDescuento.setScale(2, BigDecimal.ROUND_HALF_UP).toEngineeringString());

            objeto1.setSubtotal(subtotal);
            objeto1.setDescuento(porcentaje);
            objeto1.setIva(iva);
            objeto1.setTotal(TotalnenosDescuento);
            System.out.println("descuento " + porcentaje);
            System.out.println("total menos descuento " + TotalnenosDescuento);

        }


    }//GEN-LAST:event_TxtDescuentoPorcentajeKeyReleased

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!TxtProdSubtotal.getText().equals("")) {

            int r = JOptionPane.showConfirmDialog(null, "¿Desea modificar los datos?", "", JOptionPane.YES_NO_OPTION);
            if (r == JOptionPane.YES_OPTION) {
                TxtDescuentoPorcentaje.setEditable(true);
            }
        }
        /*   if (!TxtProdSubtotal.getText().equals("")) {

         VerificarAcceso va = new VerificarAcceso(new javax.swing.JFrame(), true);

         va.setVisible(true);

         if (va.devolverBandera().equals("si")) {
         TxtDescuentoPorcentaje.setEditable(true);
         }

         }*/


    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

        if (jCheckBox1.isEnabled()) {

            TxtCedula.setText("9999999999");
            TxtNombre.setText("CONSUMIDOR FINAL XXXXXXXXX");
            TxtCorreo.setText("xxxxx@gmail.com");
            TxtDirec.setText("xxxxxxxxxxx");
            TxtTelefono.setText("0000000000 CONVENCIONAL");
            TxtProdNombre.setEnabled(true);
            TxtProdPrecio.setEnabled(true);
            TxtProdCantidad.setEnabled(true);
            TxtProdSubtotal.setEnabled(true);
            TxtDescuentoPorcentaje.setEnabled(true);
            TxtProdDescuento.setEnabled(true);
            TxtProdIva.setEnabled(true);
            TxtProdtotal.setEnabled(true);
            TxtProdNombre.setEditable(false);
            TxtProdPrecio.setEditable(false);
            TxtProdCantidad.setEditable(true);
            TxtProdSubtotal.setEditable(false);
            TxtDescuentoPorcentaje.setEditable(false);
            TxtProdDescuento.setEditable(false);
            TxtProdIva.setEditable(false);
            TxtProdtotal.setEditable(false);
        }
        if (!jCheckBox1.isSelected()) {
            TxtCedula.setText("");
            TxtNombre.setText("");
            TxtCorreo.setText("");
            TxtDirec.setText("");
            TxtTelefono.setText("");
            TxtProdNombre.setEnabled(false);
            TxtProdPrecio.setEnabled(false);
            TxtProdCantidad.setEnabled(false);
            TxtProdSubtotal.setEnabled(false);
            TxtDescuentoPorcentaje.setEnabled(false);
            TxtProdDescuento.setEnabled(false);
            TxtProdIva.setEnabled(false);
            TxtProdtotal.setEnabled(false);
            TxtProdNombre.setEditable(true);
            TxtProdPrecio.setEditable(true);
            TxtProdCantidad.setEditable(false);
            TxtProdSubtotal.setEditable(true);
            TxtDescuentoPorcentaje.setEditable(true);
            TxtProdDescuento.setEditable(true);
            TxtProdIva.setEditable(true);
            TxtProdtotal.setEditable(true);
        }


    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPreVentas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPreVentas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPreVentas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPreVentas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPreVentas dialog = new MenuPreVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddIten;
    private javax.swing.JButton BtnBuscarcedula;
    private javax.swing.JButton BtnBuscarprodnombre;
    private javax.swing.JButton BtnGenerarVenta;
    private javax.swing.JComboBox<String> CbxFormaPago;
    private javax.swing.JComboBox<String> CbxTipoVenta;
    private javax.swing.JTable TablaListarVentas;
    private javax.swing.JTextField TxtCedula;
    public static javax.swing.JTextField TxtCorreo;
    private javax.swing.JTextField TxtDescuento;
    private javax.swing.JTextField TxtDescuentoPorcentaje;
    private javax.swing.JTextField TxtDirec;
    private javax.swing.JTextField TxtIva;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtProdCantidad;
    private javax.swing.JTextField TxtProdDescuento;
    private javax.swing.JTextField TxtProdIva;
    private javax.swing.JTextField TxtProdNombre;
    private javax.swing.JTextField TxtProdPrecio;
    private javax.swing.JTextField TxtProdSubtotal;
    private javax.swing.JTextField TxtProdtotal;
    private javax.swing.JTextField TxtSubtotal;
    private javax.swing.JTextField TxtSubtotalconIva;
    private javax.swing.JTextField TxtSubtotalsinIva;
    private javax.swing.JTextField TxtTelefono;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCerrar;
    // End of variables declaration//GEN-END:variables
}
